In [1]:
import pandas as pd

In [2]:
matches=pd.read_csv("scrapped_data.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2022,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,0.0,2022,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,Match Report,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2022,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2022,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,0.0,2022,Manchester City

In [4]:
matches["team"].value_counts()

Manchester City             76
Crystal Palace              76
Southampton                 76
Leeds United                76
Leicester City              76
Everton                     76
West Ham United             76
Wolverhampton Wanderers     76
Arsenal                     76
Chelsea                     76
Brentford                   76
Tottenham Hotspur           76
Aston Villa                 76
Brighton and Hove Albion    76
Liverpool                   76
Newcastle United            76
Manchester United           76
Fulham                      38
Bournemouth                 38
Nottingham Forest           38
Burnley                     38
Watford                     38
Norwich City                38
Name: team, dtype: int64

In [5]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [6]:
matches["date"] = pd.to_datetime(matches["date"])

In [7]:
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                       int64
ga                       int64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
dtype: object

In [8]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [9]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,notes,sh,sot,dist,fk,pk,pkatt,season,team,venue_code
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2022,Manchester City,0
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,NaN,19.0,7.0,17.5,0.0,0.0,0.0,2022,Manchester City,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2022,Manchester City,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2022,Manchester City,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,NaN,17.0,9.0,14.8,0.0,0.0,0.0,2022,Manchester City,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,NaN,9.0,3.0,21.6,0.0,0.0,0.0,2021,Norwich City,0
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,NaN,8.0,2.0,22.2,1.0,0.0,0.0,2021,Norwich City,1
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,NaN,9.0,5.0,17.0,0.0,0.0,0.0,2021,Norwich City,0
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,NaN,11.0,2.0,14.4,0.0,0.0,0.0,2021,Norwich City,0
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,NaN,9.0,0.0,18.6,0.0,0.0,0.0,2021,Norwich City,1

In [10]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [11]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [12]:
matches["day_code"] = matches["date"].dt.dayofweek

In [13]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,dist,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,18.7,1.0,1.0,1.0,2022,Manchester City,0,21,16,6
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,17.5,0.0,0.0,0.0,2022,Manchester City,1,2,15,5
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,16.2,1.0,0.0,0.0,2022,Manchester City,0,15,16,6
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,14.1,0.0,0.0,0.0,2022,Manchester City,1,7,15,5
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,14.8,0.0,0.0,0.0,2022,Manchester City,1,17,19,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,21.6,0.0,0.0,0.0,2021,Norwich City,0,1,15,5
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,22.2,1.0,0.0,0.0,2021,Norwich City,1,21,14,6
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,17.0,0.0,0.0,0.0,2021,Norwich City,0,11,19,2
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,14.4,0.0,0.0,0.0,2021,Norwich City,0,22,14,6
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,18.6,0.0,0.0,0.0,2021,Norwich City,1,19,16,6

In [14]:
matches["target"] = (matches["result"] == "W").astype("int")

In [15]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,1.0,1.0,1.0,2022,Manchester City,0,21,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,0.0,0.0,0.0,2022,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,1.0,0.0,0.0,2022,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,0.0,0.0,0.0,2022,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,0.0,0.0,0.0,2022,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Aston Villa,...,0.0,0.0,0.0,2021,Norwich City,0,1,15,5,0
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0,4,West Ham,...,1.0,0.0,0.0,2021,Norwich City,1,21,14,6,0
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0,3,Leicester City,...,0.0,0.0,0.0,2021,Norwich City,0,11,19,2,0
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1,1,Wolves,...,0.0,0.0,0.0,2021,Norwich City,0,22,14,6,0
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0,5,Tottenham,...,0.0,0.0,0.0,2021,Norwich City,1,19,16,6,0

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [69]:
train=matches[matches["date"] < '2023-01-01']

In [70]:
test=matches[matches["date"] > '2023-01-01']

In [71]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [72]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [73]:
preds = rf.predict(test[predictors])

In [74]:
from sklearn.metrics import accuracy_score

In [75]:
error = accuracy_score(test["target"], preds)

In [76]:
error

0.5981308411214953

In [77]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [78]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          203  60
1          112  53

In [79]:
from sklearn.metrics import precision_score

In [80]:
precision_score(test["target"], preds)

0.4690265486725664

In [81]:
grouped_matches = matches.groupby("team")

In [82]:
group = grouped_matches.get_group("Manchester United").sort_values("date")

In [83]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [84]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,4,1,Newcastle Utd,...,5,1,2.333333,0.666667,13.666667,4.666667,17.366667,0.666667,0.000000,0.000000
5,2021-09-19,14:00,Premier League,Matchweek 5,Sun,Away,W,2,1,West Ham,...,6,1,2.000000,0.666667,15.333333,4.000000,18.133333,0.666667,0.000000,0.000000
7,2021-09-25,12:30,Premier League,Matchweek 6,Sat,Home,L,0,1,Aston Villa,...,5,0,2.333333,0.666667,16.000000,6.333333,18.800000,0.333333,0.000000,0.000000
9,2021-10-02,12:30,Premier League,Matchweek 7,Sat,Home,D,1,1,Everton,...,5,0,2.000000,1.000000,21.666667,6.666667,19.100000,0.666667,0.000000,0.333333
10,2021-10-16,15:00,Premier League,Matchweek 8,Sat,Away,L,2,4,Leicester City,...,5,0,1.000000,1.000000,19.000000,6.666667,17.300000,0.666667,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,2023-05-07,19:00,Premier League,Matchweek 35,Sun,Away,L,0,1,West Ham,...,6,0,1.000000,1.000000,15.666667,6.000000,18.466667,1.000000,0.000000,0.000000
57,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,W,2,0,Wolves,...,5,1,0.333333,0.666667,16.333333,5.000000,18.566667,0.333333,0.000000,0.000000
58,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Away,W,1,0,Bournemouth,...,5,1,0.666667,0.666667,20.666667,6.000000,18.666667,1.000000,0.000000,0.000000
59,2023-05-25,20:00,Premier League,Matchweek 32,Thu,Home,W,4,1,Chelsea,...,3,1,1.000000,0.333333,22.000000,6.000000,18.733333,0.666667,0.000000,0.000000
60,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,W,2,1,Fulham,...,6,1,2.333333,0.333333,21.333333,7.333333,17.766667,0.666667,0.333333,0.333333

In [85]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [86]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 4  2021-09-11  15:00  Premier League   Matchweek 4
                        5  2021-09-18  15:00  Premier League   Matchweek 5
                        7  2021-09-26  16:30  Premier League   Matchweek 6
                        8  2021-10-02  17:30  Premier League   Matchweek 7
                        9  2021-10-18  20:00  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 39 2023-04-29  15:00  Premier League  Matchweek 34
                        40 2023-05-06  15:00  Premier League  Matchweek 35
                        41 2023-05-13  15:00  Premier League  Matchweek 36
                        42 2023-05-20  15:00  Premier League  Matchweek 37
                        43 2023-05-28  16:30  Premier League  Matchweek 38

                            day venue result  gf  ga        opponent  ...  \
team                                                                  ...
Arsenal                 4   Sat  Home      W   1   0    Norwich City  ...
                        5   Sat  Away      W   1   0         Burnley  ...
                        7   Sun  Home      W   3   1       Tottenham  ...
                        8   Sat  Away      D   0   0        Brighton  ...
                        9   Mon  Home      D   2   2  Crystal Palace  ...
...                         ...   ...    ...  ..  ..             ...  ...
Wolverhampton Wanderers 39  Sat  Away      L   0   6        Brighton  ...
                        40  Sat  Home      W   1   0     Aston Villa  ...
                        41  Sat  Away      L   0   2  Manchester Utd  ...
                        42  Sat  Home      D   1   1         Everton  ...
                        43  Sun  Away      L   0   5         Arsenal  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 4          5       1    0.000000    3.000000
                        5          5       1    0.333333    2.333333
                        7          6       1    0.666667    1.666667
                        8          5       0    1.666667    0.333333
                        9          0       0    1.333333    0.333333
...                              ...     ...         ...         ...
Wolverhampton Wanderers 39         5       0    1.666667    0.666667
                        40         5       1    1.000000    2.666667
                        41         5       0    1.000000    2.000000
                        42         5       0    0.333333    2.666667
                        43         6       0    0.666667    1.000000

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 4    9.666667    2.333333    14.833333   0.333333
                        5   12.333333    3.000000    14.133333   0.333333
                        7   14.666667    3.000000    14.800000   0.666667
                        8   18.333333    5.333333    18.433333   0.666667
                        9   11.000000    4.000000    19.833333   0.666667
...                               ...         ...          ...        ...
Wolverhampton Wanderers 39  11.666667    4.666667    18.700000   0.666667
                        40  11.333333    2.333333    18.800000   0.666667
                        41   8.000000    2.000000    17.766667   0.000000
                        42   7.000000    1.333333    15.600000   0.000000
                        43   8.000000    2.333333    15.333333   0.333333

                            pk_rolling  pkatt_rolling
team
Arsenal                 4     0.000000       0.000000
                        5     0.000000       0.000000
                        7     0.000000       0.000000
                        8     0.000000       0.000000
                        9     0.000000       0.000000
...                                ...            ...
Wolverhampton Wanderers 39    0.333333       0.333333
                        40    0.333333       0.333333
                        41    0.333333       0.333333
                        42    0.000000       0.000000
                        43    0.000000       0.000000

[1451 rows x 40 columns]

In [87]:
matches_rolling = matches_rolling.droplevel('team')

In [88]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1,0,Norwich City,...,5,1,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.000000,0.000000
5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1,0,Burnley,...,5,1,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.000000,0.000000
7,2021-09-26,16:30,Premier League,Matchweek 6,Sun,Home,W,3,1,Tottenham,...,6,1,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.000000,0.000000
8,2021-10-02,17:30,Premier League,Matchweek 7,Sat,Away,D,0,0,Brighton,...,5,0,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.000000,0.000000
9,2021-10-18,20:00,Premier League,Matchweek 8,Mon,Home,D,2,2,Crystal Palace,...,0,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0,6,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
40,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1,0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
41,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0,2,Manchester Utd,...,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
42,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1,1,Everton,...,5,0,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
43,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,5,Arsenal,...,6,0,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

In [101]:
matches_rolling.index = range(matches_rolling.shape[0])

In [102]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2023-01-01']
    test = data[data["date"] > '2023-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [103]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [104]:
error

0.5612244897959183

In [105]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [106]:
combined.head(20)

    actual  predicted       date     team         opponent result
51       0          1 2023-01-03  Arsenal    Newcastle Utd      D
52       1          1 2023-01-15  Arsenal        Tottenham      W
53       1          1 2023-01-22  Arsenal   Manchester Utd      W
54       0          1 2023-02-04  Arsenal          Everton      L
55       0          1 2023-02-11  Arsenal        Brentford      D
56       0          0 2023-02-15  Arsenal  Manchester City      L
57       1          1 2023-02-18  Arsenal      Aston Villa      W
58       1          1 2023-02-25  Arsenal   Leicester City      W
59       1          0 2023-03-01  Arsenal          Everton      W
60       1          1 2023-03-04  Arsenal      Bournemouth      W
61       1          1 2023-03-12  Arsenal           Fulham      W
62       1          1 2023-03-19  Arsenal   Crystal Palace      W
63       1          1 2023-04-01  Arsenal     Leeds United      W
64       0          0 2023-04-09  Arsenal        Liverpool      D
65       0          0 2023-04-16  Arsenal         West Ham      D
66       0          0 2023-04-21  Arsenal      Southampton      D
67       0          0 2023-04-26  Arsenal  Manchester City      L
68       1          0 2023-05-02  Arsenal          Chelsea      W
69       1          0 2023-05-07  Arsenal    Newcastle Utd      W
70       0          0 2023-05-14  Arsenal         Brighton      L

In [107]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [108]:
mapping

{'Brighton and Hove Albion': 'Brighton',
 'Manchester United': 'Manchester Utd',
 'Newcastle United': 'Newcastle Utd',
 'Tottenham Hotspur': 'Tottenham',
 'West Ham United': 'West Ham',
 'Wolverhampton Wanderers': 'Wolves'}

In [109]:
combined["new_team"] = combined["team"].map(mapping)

In [110]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [111]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal,0,0,Newcastle United,Arsenal,D,Newcastle Utd
1,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
2,1,1,2023-01-22,Arsenal,Manchester Utd,W,Arsenal,0,1,Manchester United,Arsenal,L,Manchester Utd
3,0,1,2023-02-04,Arsenal,Everton,L,Arsenal,1,0,Everton,Arsenal,W,Everton
4,0,1,2023-02-11,Arsenal,Brentford,D,Arsenal,0,0,Brentford,Arsenal,D,Brentford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton
403,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,1,Aston Villa,Wolves,L,Aston Villa
404,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,1,Manchester United,Wolves,W,Manchester Utd
405,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves,0,0,Everton,Wolves,D,Everton
406,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves,1,0,Arsenal,Wolves,W,Arsenal

In [112]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    49
0    32
Name: actual_x, dtype: int64

In [113]:
49/(49+32)

0.6049382716049383